

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PK_UI;

import java.awt.BorderLayout;
import java.sql.SQLException;
import javax.swing.JPanel;
import PK_Utilidades.Opciones;

/**
 *
 * @author amgoo
 */
public class Desafio2Frame extends javax.swing.JFrame {


    
    /**
     * Creates new form Desafio2TestFrame
     */
    public Desafio2Frame() {
        initComponents();
        setLocationW();
    }
    
    private void setLocationW(){
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        agregarMaterial = new javax.swing.JButton();
        modificarMaterial = new javax.swing.JButton();
        listarDisponible = new javax.swing.JButton();
        borrarMaterial = new javax.swing.JButton();
        buscarMaterial = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        prestarMaterial = new javax.swing.JButton();
        contenedor = new javax.swing.JPanel();
        principal1 = new javax.swing.JPanel();
        titulo1 = new javax.swing.JLabel();
        agregarMaterial1 = new javax.swing.JButton();
        modificarMaterial1 = new javax.swing.JButton();
        listarDisponible1 = new javax.swing.JButton();
        borrarMaterial1 = new javax.swing.JButton();
        buscarMaterial1 = new javax.swing.JButton();
        salir1 = new javax.swing.JButton();
        prestarMaterial1 = new javax.swing.JButton();
        contenedor1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        titulo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("MEDIATECA");

        agregarMaterial.setText("Agregar Material");
        agregarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMaterialActionPerformed(evt);
            }
        });

        modificarMaterial.setText("Modificar Material");
        modificarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarMaterialActionPerformed(evt);
            }
        });

        listarDisponible.setText("Listar Disponible");
        listarDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarDisponibleActionPerformed(evt);
            }
        });

        borrarMaterial.setText("Borrar Material");
        borrarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarMaterialActionPerformed(evt);
            }
        });

        buscarMaterial.setText("Buscar Material");
        buscarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMaterialActionPerformed(evt);
            }
        });

        salir.setBackground(java.awt.Color.red);
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        prestarMaterial.setText("Prestamos");
        prestarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestarMaterialActionPerformed(evt);
            }
        });

        contenedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contenedor.setMaximumSize(new java.awt.Dimension(0, 0));
        contenedor.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(borrarMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listarDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modificarMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregarMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prestarMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(principalLayout.createSequentialGroup()
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(agregarMaterial)
                        .addGap(18, 18, 18)
                        .addComponent(modificarMaterial)
                        .addGap(18, 18, 18)
                        .addComponent(buscarMaterial)
                        .addGap(18, 18, 18)
                        .addComponent(borrarMaterial)
                        .addGap(18, 18, 18)
                        .addComponent(listarDisponible)
                        .addGap(18, 18, 18)
                        .addComponent(prestarMaterial)
                        .addGap(134, 134, 134)
                        .addComponent(salir))
                    .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        titulo1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("MEDIATECA");

        agregarMaterial1.setText("Agregar Material");
        agregarMaterial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMaterial1ActionPerformed(evt);
            }
        });

        modificarMaterial1.setText("Modificar Material");
        modificarMaterial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarMaterial1ActionPerformed(evt);
            }
        });

        listarDisponible1.setText("Listar Disponible");
        listarDisponible1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarDisponible1ActionPerformed(evt);
            }
        });

        borrarMaterial1.setText("Borrar Material");
        borrarMaterial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarMaterial1ActionPerformed(evt);
            }
        });

        buscarMaterial1.setText("Buscar Material");
        buscarMaterial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMaterial1ActionPerformed(evt);
            }
        });

        salir1.setBackground(java.awt.Color.red);
        salir1.setText("Salir");
        salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir1ActionPerformed(evt);
            }
        });

        prestarMaterial1.setText("Prestamos");
        prestarMaterial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestarMaterial1ActionPerformed(evt);
            }
        });

        contenedor1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contenedor1.setMaximumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout contenedor1Layout = new javax.swing.GroupLayout(contenedor1);
        contenedor1.setLayout(contenedor1Layout);
        contenedor1Layout.setHorizontalGroup(
            contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        contenedor1Layout.setVerticalGroup(
            contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout principal1Layout = new javax.swing.GroupLayout(principal1);
        principal1.setLayout(principal1Layout);
        principal1Layout.setHorizontalGroup(
            principal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principal1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(principal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(borrarMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listarDisponible1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modificarMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregarMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prestarMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(contenedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        principal1Layout.setVerticalGroup(
            principal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principal1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(principal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(principal1Layout.createSequentialGroup()
                        .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(agregarMaterial1)
                        .addGap(18, 18, 18)
                        .addComponent(modificarMaterial1)
                        .addGap(18, 18, 18)
                        .addComponent(buscarMaterial1)
                        .addGap(18, 18, 18)
                        .addComponent(borrarMaterial1)
                        .addGap(18, 18, 18)
                        .addComponent(listarDisponible1)
                        .addGap(18, 18, 18)
                        .addComponent(prestarMaterial1)
                        .addGap(134, 134, 134)
                        .addComponent(salir1))
                    .addComponent(contenedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(principal1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE)
                .addComponent(principal1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMaterialActionPerformed
        // TODO add your handling code here:
        AgregarMaterial opcionAgregar = new AgregarMaterial();
        ShowOption(opcionAgregar);
        Opciones.opcionAgregar = true;
        Opciones.opcionBuscar= false;
        Opciones.opcionModificar= false;
    }//GEN-LAST:event_agregarMaterialActionPerformed

    private void modificarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarMaterialActionPerformed
        // TODO add your handling code here:
        ModificarMaterial opcionModificar = new ModificarMaterial();
        ShowOption(opcionModificar);
        Opciones.opcionAgregar = false;
        Opciones.opcionBuscar= false;
        Opciones.opcionModificar= true;
    }//GEN-LAST:event_modificarMaterialActionPerformed

    private void listarDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarDisponibleActionPerformed
        // TODO add your handling code here:
        ListarMaterialDisponible opcionListar = new ListarMaterialDisponible();
        ShowOption(opcionListar);
    }//GEN-LAST:event_listarDisponibleActionPerformed

    private void borrarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarMaterialActionPerformed
        // TODO add your handling code here:
        BorrarMaterial opcionBorrar = new BorrarMaterial();
        ShowOption(opcionBorrar);
    }//GEN-LAST:event_borrarMaterialActionPerformed

    private void buscarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMaterialActionPerformed
        // TODO add your handling code here:
        BuscarMaterial opcionBuscar = new BuscarMaterial();
        ShowOption(opcionBuscar);
        Opciones.opcionAgregar = false;
        Opciones.opcionBuscar= true;
        Opciones.opcionModificar= false;
    }//GEN-LAST:event_buscarMaterialActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void prestarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestarMaterialActionPerformed
        PrestarDevolverMat opcionPrestar = new PrestarDevolverMat();
        ShowOption(opcionPrestar);
    }//GEN-LAST:event_prestarMaterialActionPerformed

    private void agregarMaterial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMaterial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarMaterial1ActionPerformed

    private void modificarMaterial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarMaterial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarMaterial1ActionPerformed

    private void listarDisponible1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarDisponible1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarDisponible1ActionPerformed

    private void borrarMaterial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarMaterial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarMaterial1ActionPerformed

    private void buscarMaterial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMaterial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarMaterial1ActionPerformed

    private void salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salir1ActionPerformed

    private void prestarMaterial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestarMaterial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prestarMaterial1ActionPerformed
    
    private void ShowOption(JPanel p){
        p.setSize(440, 450);
        p.setLocation(0,0);
        
        contenedor.removeAll();
        contenedor.add(p, BorderLayout.CENTER);
        contenedor.revalidate();
        contenedor.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desafio2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desafio2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desafio2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desafio2Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desafio2Frame().setVisible(true);
            }
        });
        //Comprobando conexion con db             
        PK_Utilidades.ConeccionBD cn = new PK_Utilidades.ConeccionBD ();
        if(cn.getConexion() !=null){
             System.out.println ("Conexión correcta");
        }
        else{
            System.out.println("Conexión erronea");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarMaterial;
    private javax.swing.JButton agregarMaterial1;
    private javax.swing.JButton borrarMaterial;
    private javax.swing.JButton borrarMaterial1;
    private javax.swing.JButton buscarMaterial;
    private javax.swing.JButton buscarMaterial1;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel contenedor1;
    private javax.swing.JButton listarDisponible;
    private javax.swing.JButton listarDisponible1;
    private javax.swing.JButton modificarMaterial;
    private javax.swing.JButton modificarMaterial1;
    private javax.swing.JButton prestarMaterial;
    private javax.swing.JButton prestarMaterial1;
    private javax.swing.JPanel principal;
    private javax.swing.JPanel principal1;
    private javax.swing.JButton salir;
    private javax.swing.JButton salir1;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables

}
