/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PK_UI;

import PK_Modelos.ObjetoRevista;
import PK_Repositorios.CRUDRev;
import PK_Utilidades.Opciones;
import java.awt.event.KeyEvent;



/**
 *
 * @author admin
 */
public class panelRevista extends javax.swing.JPanel {
    private final CRUDRev insertarRevista;
    private final ObjetoRevista Setrevista;
    /**
     * Creates new form panelRevista
     */
    public panelRevista() {
        initComponents();
        Setrevista = new ObjetoRevista();
        insertarRevista = new CRUDRev();
        agregarDatos.setVisible(Opciones.opcionAgregar);
        modificar.setVisible(Opciones.opcionModificar);
        jTextCodigo.setVisible(Opciones.opcionModificar);
        jLabel6.setVisible(Opciones.opcionModificar);
        buscarDatos.setVisible(Opciones.opcionBuscar);
        if (Opciones.opcionAgregar){
            anioPublicacion.setVisible(Opciones.opcionAgregar);
            jLabel4.setVisible(Opciones.opcionAgregar);
            jLabel8.setVisible(Opciones.opcionBuscar);
        }else if (Opciones.opcionModificar){
            anioPublicacion.setVisible(Opciones.opcionModificar);
            jLabel4.setVisible(Opciones.opcionModificar);
            jLabel8.setVisible(Opciones.opcionBuscar);        
        }else if (Opciones.opcionBuscar){
            anioPublicacion.setVisible(false);
            unidadesDis.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
        }
        modificar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        editorial = new javax.swing.JTextField();
        periodicidad = new javax.swing.JTextField();
        unidadesDis = new javax.swing.JTextField();
        anioPublicacion = new javax.swing.JTextField();
        agregarDatos = new javax.swing.JButton();
        buscarDatos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMostrar = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        modificar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setText("Titulo:");

        jLabel2.setText("Editorial:");

        jLabel3.setText("Periodicidad:");

        jLabel4.setText("Año de publicación:");

        jLabel5.setText("Cantidad Total:");

        agregarDatos.setText("Agregar");
        agregarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDatosActionPerformed(evt);
            }
        });

        buscarDatos.setText("Buscar");
        buscarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDatosActionPerformed(evt);
            }
        });

        jMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jMostrar);

        jLabel6.setText("Codigo Material:");

        jTextCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextCodigoKeyPressed(evt);
            }
        });

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("* agregar % para realizar una busqueda por Parcial");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(anioPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(unidadesDis, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(agregarDatos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(modificar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                            .addComponent(buscarDatos))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6))
                            .addGap(7, 7, 7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                                .addComponent(editorial)
                                .addComponent(periodicidad)
                                .addComponent(jTextCodigo)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(periodicidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anioPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(unidadesDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarDatos)
                    .addComponent(buscarDatos)
                    .addComponent(modificar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarDatosActionPerformed
 //variables
        int anioPublic,IDrevista;

        Setrevista.setTipo(2);
        Setrevista.setTitulo(titulo.getText());
        Setrevista.setEditorial(editorial.getText());
        Setrevista.setPeriodicidad(periodicidad.getText());

        anioPublic = Integer.parseInt(anioPublicacion.getText());
        Setrevista.setFecha_publ(anioPublic);

        String IDcantd = insertarRevista.NumRandom();
        
        int CantD = Integer.parseInt(unidadesDis.getText());
        int CantT = CantD;
        
        
        IDrevista =insertarRevista.insertarDatos(Setrevista);
        
        insertarRevista.insertmaterialdisponible(IDcantd,CantD, CantT, IDrevista);        // TODO add your handling code here:
    }//GEN-LAST:event_agregarDatosActionPerformed

    private void buscarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDatosActionPerformed
        int anioPublic;

        Setrevista.setTitulo(titulo.getText());
        Setrevista.setEditorial(editorial.getText());
        Setrevista.setPeriodicidad(periodicidad.getText());
//        anioPublic = Integer.parseInt(anioPublicacion.getText());
//        Setrevista.setFecha_publ(anioPublic);

        jMostrar.setModel(insertarRevista.select(Setrevista));
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarDatosActionPerformed

    private void jTextCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCodigoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //metodoselectModificar
            ObjetoRevista revistaMod = insertarRevista.selectId(jTextCodigo.getText());
            titulo.setText(revistaMod.titulo);
            editorial.setText(revistaMod.Editorial);
            periodicidad.setText(revistaMod.Periodicidad);
            anioPublicacion.setText(String.valueOf(revistaMod.Fecha_publ));
            unidadesDis.setText(String.valueOf(insertarRevista.selectCant()));
            modificar.setEnabled(true);
        }
    }//GEN-LAST:event_jTextCodigoKeyPressed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        int cantT;

        Setrevista.setTitulo(titulo.getText());
        Setrevista.setEditorial(editorial.getText());
        Setrevista.setPeriodicidad(periodicidad.getText());
        Setrevista.setFecha_publ(Integer.parseInt(anioPublicacion.getText()));
        
        cantT = Integer.parseInt(unidadesDis.getText());
        
        insertarRevista.updateDatos(Setrevista);
        insertarRevista.updateMaterial(cantT, jTextCodigo.getText());
        clear();
        modificar.setEnabled(false);
    }//GEN-LAST:event_modificarActionPerformed

    private void clear(){
        titulo.setText("");
        editorial.setText("");
        periodicidad.setText("");
        anioPublicacion.setText("");
        unidadesDis.setText("");
        jTextCodigo.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarDatos;
    private javax.swing.JTextField anioPublicacion;
    private javax.swing.JButton buscarDatos;
    private javax.swing.JTextField editorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTable jMostrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField periodicidad;
    private javax.swing.JTextField titulo;
    private javax.swing.JTextField unidadesDis;
    // End of variables declaration//GEN-END:variables
}
