package PK_UI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import PK_Modelos.ObjetoDvd;
import PK_Repositorios.CRUDDvd;
import PK_Utilidades.Opciones;
import java.awt.event.KeyEvent;

/**
 *
 * @author admin
 */
public class panelDvd extends javax.swing.JPanel {
    private final CRUDDvd insertarDVD;
    private final ObjetoDvd SetDvd; 
    /**
     * Creates new form panel
     */
    public panelDvd() {
        initComponents();
        SetDvd = new ObjetoDvd();
        insertarDVD = new CRUDDvd();
        
        agregar.setVisible(Opciones.opcionAgregar);
        modificar.setVisible(Opciones.opcionModificar);
        tcodigo.setVisible(Opciones.opcionModificar);
        jcodigo.setVisible(Opciones.opcionModificar);
        buscar.setVisible(Opciones.opcionBuscar);
        if (Opciones.opcionAgregar){
            tgenero.setVisible(Opciones.opcionAgregar);
            jdirector.setVisible(Opciones.opcionAgregar);
            jduracion.setVisible(Opciones.opcionAgregar);
            jtexto.setVisible(Opciones.opcionBuscar);
        }else if (Opciones.opcionModificar){
            tgenero.setVisible(Opciones.opcionModificar);
            jdirector.setVisible(Opciones.opcionModificar);
            jduracion.setVisible(Opciones.opcionModificar);
            jtexto.setVisible(Opciones.opcionBuscar);
            buscar.setVisible(false);
            modificar.setEnabled(true);
        }else if (Opciones.opcionBuscar){     
            tcodigo.setVisible(false);
            jcodigo.setVisible(false);
            junidades.setVisible(false);
            tunidades.setVisible(false);
            modificar.setEnabled(false);
        }     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtitulo = new javax.swing.JLabel();
        jdirector = new javax.swing.JLabel();
        jduracion = new javax.swing.JLabel();
        jgenero = new javax.swing.JLabel();
        ttitulo = new javax.swing.JTextField();
        tdirector = new javax.swing.JTextField();
        tgenero = new javax.swing.JTextField();
        tduracion = new javax.swing.JTextField();
        contenedor = new javax.swing.JScrollPane();
        jMostrar = new javax.swing.JTable();
        agregar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        junidades = new javax.swing.JLabel();
        tunidades = new javax.swing.JTextField();
        jtexto = new javax.swing.JLabel();
        jcodigo = new javax.swing.JLabel();
        modificar = new javax.swing.JButton();
        tcodigo = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jtitulo.setText("Titulo:");

        jdirector.setText("Director:");

        jduracion.setText("Duracion:");

        jgenero.setText("Genero:");

        jMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        contenedor.setViewportView(jMostrar);

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        junidades.setText("Unidades Disponibles:");

        jtexto.setForeground(new java.awt.Color(204, 0, 0));
        jtexto.setText("* agregar % para realizar una busqueda por Parcial");

        jcodigo.setText("Codigo a Modificar");

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        tcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tcodigoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdirector, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(jduracion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tduracion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tdirector)
                            .addComponent(ttitulo)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(junidades)
                        .addGap(18, 18, 18)
                        .addComponent(tunidades))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtexto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tcodigo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtexto)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcodigo)
                    .addComponent(tcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtitulo)
                    .addComponent(ttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdirector)
                    .addComponent(tdirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jgenero)
                    .addComponent(tgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tduracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jduracion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tunidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(junidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(agregar)
                        .addComponent(modificar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        int IDDVD;

        SetDvd.setTipo(2);
        SetDvd.setTitulo(ttitulo.getText());
        SetDvd.setDirector(tdirector.getText());      
        SetDvd.setGenero(tgenero.getText());
        SetDvd.setDuracion(tduracion.getText());

        String IDcantd = insertarDVD.NumRandom();
        System.out.println(IDcantd);
        int CantD = Integer.parseInt(tunidades.getText());
        int CantT = CantD;
        
        
        IDDVD =insertarDVD.insertarDatos(SetDvd);
        System.out.println(IDDVD);
        
        insertarDVD.insertmaterialdisponible(IDcantd,CantD, CantT, IDDVD);        // TODO add your handling code here:
         // TODO add your handling code here:
    }//GEN-LAST:event_agregarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

        SetDvd.setTipo(1);
        SetDvd.setTitulo(ttitulo.getText());
        SetDvd.setDirector(tdirector.getText());
        SetDvd.setGenero(tgenero.getText());
        SetDvd.setDuracion(tduracion.getText());
        tunidades.setText(String.valueOf(insertarDVD.selectCant()));

        jMostrar.setModel(insertarDVD.select(SetDvd));
        mostrar();

           // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed
    private void mostrar(){
            ObjetoDvd dvdmod = insertarDVD.selectId(tcodigo.getText());
            ttitulo.setText(dvdmod.titulo);
            tdirector.setText(dvdmod.director);
            tgenero.setText(dvdmod.genero);
            tduracion.setText(dvdmod.duracion);
            modificar.setEnabled(true);
    }
    
    private void tcodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcodigoKeyPressed
        // TODO add your handling code here:
                if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //metodoselectModificar
            ObjetoDvd dvdmod = insertarDVD.selectId(tcodigo.getText());
            ttitulo.setText(dvdmod.titulo);
            tdirector.setText(dvdmod.director);
            tgenero.setText(dvdmod.genero);
            tduracion.setText(dvdmod.duracion);
            tunidades.setText(String.valueOf(insertarDVD.selectCant()));
            modificar.setEnabled(true);
        }
    }//GEN-LAST:event_tcodigoKeyPressed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        int cantT;

        SetDvd.setTipo(1);
        SetDvd.setTitulo(ttitulo.getText());
        SetDvd.setDirector(tdirector.getText());
        SetDvd.setGenero(tgenero.getText());
        SetDvd.setDuracion(tduracion.getText());
        
        cantT = Integer.parseInt(tunidades.getText());
        
        insertarDVD.updateDatos(SetDvd);
        insertarDVD.updateMaterial(cantT, tcodigo.getText());
        clear();
        modificar.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_modificarActionPerformed
    
    private void clear(){
        tcodigo.setText("");
        ttitulo.setText("");
        tdirector.setText("");
        tduracion.setText("");
        tgenero.setText("");
        tunidades.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton buscar;
    private javax.swing.JScrollPane contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jMostrar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jcodigo;
    private javax.swing.JLabel jdirector;
    private javax.swing.JLabel jduracion;
    private javax.swing.JLabel jgenero;
    private javax.swing.JLabel jtexto;
    private javax.swing.JLabel jtitulo;
    private javax.swing.JLabel junidades;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField tcodigo;
    private javax.swing.JTextField tdirector;
    private javax.swing.JTextField tduracion;
    private javax.swing.JTextField tgenero;
    private javax.swing.JTextField ttitulo;
    private javax.swing.JTextField tunidades;
    // End of variables declaration//GEN-END:variables
}
