/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PK_UI;

import PK_Repositorios.CRUDLibro;
import PK_Modelos.ObjetoLibro;
import java.awt.event.KeyEvent;
import PK_Utilidades.Opciones;

/**
 *
 * @author admin
 */
public class panelLibro extends javax.swing.JPanel {

    private final CRUDLibro insertarLibro;
    private final ObjetoLibro Setlibro;

    /**
     * Creates new form PanelLibro
     */
    public panelLibro() {
        initComponents();
        Setlibro = new ObjetoLibro();
        insertarLibro = new CRUDLibro();
        agregarDatos.setVisible(Opciones.opcionAgregar);
        modificarDatos.setVisible(Opciones.opcionModificar);
        jTextCodigo.setVisible(Opciones.opcionModificar);
        jLabel7.setVisible(Opciones.opcionModificar);
        buscarDatos.setVisible(Opciones.opcionBuscar);
        if (Opciones.opcionAgregar){
            jTextPag.setVisible(Opciones.opcionAgregar);
            jLabel3.setVisible(Opciones.opcionAgregar);
            jLabel8.setVisible(Opciones.opcionBuscar);
        }else if (Opciones.opcionModificar){
            jTextPag.setVisible(Opciones.opcionModificar);
            jLabel3.setVisible(Opciones.opcionModificar);
            jLabel8.setVisible(Opciones.opcionBuscar);
        }else if (Opciones.opcionBuscar){
            jTextPag.setVisible(false);
            jTextCantT.setVisible(false);
            jLabel3.setVisible(false);
            jLabel5.setVisible(false);
        }
        modificarDatos.setEnabled(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        agregarDatos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextAutor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextEdit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextPag = new javax.swing.JTextField();
        jTextCod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextTitulo = new javax.swing.JTextField();
        buscarDatos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextCantT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMostrar = new javax.swing.JTable();
        jTextCodigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        modificarDatos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        agregarDatos.setText("Agregar");
        agregarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDatosActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre del Autor:");

        jLabel2.setText("Nombre de la editorial:");

        jLabel3.setText("Numero de paginas:");

        jLabel4.setText("Codigo ISBN:");

        jLabel6.setText("Titulo:");

        buscarDatos.setText("Buscar");
        buscarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDatosActionPerformed(evt);
            }
        });

        jLabel5.setText("Cantidad total:");

        jMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jMostrar);

        jTextCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextCodigoKeyPressed(evt);
            }
        });

        jLabel7.setText("Codigo Material a Modificar :");

        modificarDatos.setText("Modificar");
        modificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarDatosActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("* agregar % para realizar una busqueda por Parcial");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(agregarDatos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextPag, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modificarDatos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextCantT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buscarDatos, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextTitulo)
                            .addComponent(jTextCod)
                            .addComponent(jTextEdit)
                            .addComponent(jTextAutor)
                            .addComponent(jTextCodigo))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jTextCantT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarDatos)
                    .addComponent(modificarDatos)
                    .addComponent(agregarDatos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void agregarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarDatosActionPerformed
        //variables
        int paginas,IDlibro;

        Setlibro.setTipo(1);
        Setlibro.setAutor(jTextAutor.getText());
        Setlibro.setEdit(jTextEdit.getText());
        Setlibro.setTitulo(jTextTitulo.getText());
        Setlibro.setCode(jTextCod.getText());

        paginas = Integer.parseInt(jTextPag.getText());
        Setlibro.setPaginas(paginas);

        String IDcantd = insertarLibro.NumRandom();
        
        int CantD = Integer.parseInt(jTextCantT.getText());
        int CantT = CantD;
        
        
        IDlibro=insertarLibro.insertarDatos(Setlibro);
        
        insertarLibro.insertmaterialdisponible(IDcantd,CantD, CantT, IDlibro);
    }//GEN-LAST:event_agregarDatosActionPerformed

    private void buscarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDatosActionPerformed
        int paginas;

        Setlibro.setAutor(jTextAutor.getText());
        Setlibro.setEdit(jTextEdit.getText());
        Setlibro.setTitulo(jTextTitulo.getText());
        Setlibro.setCode(jTextCod.getText());

        jMostrar.setModel(insertarLibro.select(Setlibro));
    }//GEN-LAST:event_buscarDatosActionPerformed

    private void jTextCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCodigoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //metodoselectModificar
            ObjetoLibro libromod = insertarLibro.selectId(jTextCodigo.getText());
            jTextAutor.setText(libromod.autor);
            jTextEdit.setText(libromod.edit);
            jTextTitulo.setText(libromod.titulo);
            jTextCod.setText(libromod.code);
            jTextPag.setText(String.valueOf(libromod.paginas));
            jTextCantT.setText(String.valueOf(insertarLibro.selectCant()));
            modificarDatos.setEnabled(true);
        }
    }//GEN-LAST:event_jTextCodigoKeyPressed

    private void modificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarDatosActionPerformed
        // TODO add your handling code here:
        int cantT;

        Setlibro.setTipo(1);
        Setlibro.setAutor(jTextAutor.getText());
        Setlibro.setEdit(jTextEdit.getText());
        Setlibro.setTitulo(jTextTitulo.getText());
        Setlibro.setCode(jTextCod.getText());
        Setlibro.setPaginas(Integer.parseInt(jTextPag.getText()));
        
        cantT = Integer.parseInt(jTextCantT.getText());
        
        insertarLibro.updateDatos(Setlibro);
        insertarLibro.updateMaterial(cantT, jTextCodigo.getText());
        clear();
        modificarDatos.setEnabled(false);
    }//GEN-LAST:event_modificarDatosActionPerformed
    private void clear(){
        jTextCodigo.setText("");
        jTextAutor.setText("");
        jTextEdit.setText("");
        jTextTitulo.setText("");
        jTextCod.setText("");
        jTextPag.setText("");
        jTextCantT.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarDatos;
    private javax.swing.JButton buscarDatos;
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTable jMostrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextAutor;
    private javax.swing.JTextField jTextCantT;
    private javax.swing.JTextField jTextCod;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextEdit;
    private javax.swing.JTextField jTextPag;
    private javax.swing.JTextField jTextTitulo;
    private javax.swing.JButton modificarDatos;
    // End of variables declaration//GEN-END:variables
}
