/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PK_UI;

import PK_Repositorios.CRUD;

/**
 *
 * @author admin
 */
public class PrestarDevolverMat extends javax.swing.JPanel {
    private final CRUD PrestandDevol;

    /**
     * Creates new form panelPrestamo
     */
    public PrestarDevolverMat() {
        initComponents();
        PrestandDevol = new CRUD();
        cantDevolucion.setVisible(false);
        jLabel5.setVisible(false);
        cantPrestamo.setVisible(false);
        jLabel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MaterialGroup = new javax.swing.ButtonGroup();
        TipoMove = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        cantDevolucion = new javax.swing.JTextField();
        cantPrestamo = new javax.swing.JTextField();
        Prestamo = new javax.swing.JRadioButton();
        Devolucion = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        CodeMaterial = new javax.swing.JTextField();
        hacerCambios = new javax.swing.JButton();

        jLabel1.setText("Usuario:");

        jLabel2.setText("Codigo Material:");

        tipo.setText("Tipo de movimiento:");

        jLabel4.setText("Cantidad devolucion:");

        jLabel5.setText("Cantidad prestamo:");

        cantDevolucion.setText("0");

        cantPrestamo.setText("0");
        cantPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantPrestamoActionPerformed(evt);
            }
        });

        TipoMove.add(Prestamo);
        Prestamo.setText("Prestamo.");
        Prestamo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PrestamoItemStateChanged(evt);
            }
        });

        TipoMove.add(Devolucion);
        Devolucion.setText("Devolucion");
        Devolucion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DevolucionItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Presta y Devolucion de materiales");

        hacerCambios.setText("Realizar Accion");
        hacerCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hacerCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tipo)
                            .addGap(18, 18, 18)
                            .addComponent(Prestamo)
                            .addGap(72, 72, 72)
                            .addComponent(Devolucion))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hacerCambios)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CodeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addComponent(jLabel6))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(48, 48, 48)
                                            .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo)
                    .addComponent(Prestamo)
                    .addComponent(Devolucion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CodeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cantDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(30, 30, 30)
                .addComponent(hacerCambios)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hacerCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hacerCambiosActionPerformed

          int prestamo=0, devolucion=0 ;
          String codigo, tipo1="" ,usSocio, estado;
          boolean Busuario = false;
          if(Prestamo.isSelected()==true)
            {
                tipo1 = "prest";
            }
           if(Devolucion.isSelected()==true){
             tipo1 = "devol"; 
          }  
          prestamo = Integer.parseInt(cantPrestamo.getText());
          devolucion = Integer.parseInt(cantDevolucion.getText());
          
          codigo = CodeMaterial.getText();
          usSocio = usuario.getText();
          estado = "";

          Busuario = PrestandDevol.usuario(usSocio);
          int idSocio = PrestandDevol.RidSocio();
          System.out.println(Busuario);
          
          int CantNow = PrestandDevol.SELECTDisponibilidad(codigo);
          System.out.println(CantNow);
          
          PrestandDevol.UPDATEDisponibilidad(CantNow, prestamo, devolucion, codigo, estado);
          
          PrestandDevol.TablaPrestamo(Busuario, tipo1, idSocio, codigo, estado);
          
    }//GEN-LAST:event_hacerCambiosActionPerformed

    private void DevolucionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DevolucionItemStateChanged
        jLabel4.setVisible(true);
        cantDevolucion.setVisible(true);
        jLabel5.setVisible(false);
        cantPrestamo.setVisible(false);
        
    }//GEN-LAST:event_DevolucionItemStateChanged

    private void PrestamoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PrestamoItemStateChanged
        jLabel4.setVisible(false);
        cantDevolucion.setVisible(false);
        jLabel5.setVisible(true);
        cantPrestamo.setVisible(true);
    }//GEN-LAST:event_PrestamoItemStateChanged

    private void cantPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantPrestamoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodeMaterial;
    private javax.swing.JRadioButton Devolucion;
    private javax.swing.ButtonGroup MaterialGroup;
    private javax.swing.JRadioButton Prestamo;
    private javax.swing.ButtonGroup TipoMove;
    private javax.swing.JTextField cantDevolucion;
    private javax.swing.JTextField cantPrestamo;
    private javax.swing.JButton hacerCambios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel tipo;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
